apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-config
  labels:
    name: fcg-config
data: 
  #RabbitMq
  RABBITMQ_SVC: fcg-rabbitmq-masstransit
  RABBITMQ_PAYMENT_PROCESSED_QUEUE: "payment-processed-event-queue"
  RABBITMQ_PAYMENT_PROCESSED_NOT_QUEUE: "payment-processed-event-not-queue"
  RABBITMQ_USER_CREATED_NOT_QUEUE: "user-created-event-not-queue"
  RABBITMQ_ORDER_PLACED_QUEUE: "order-placed-event-queue"
  #.NetCore
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:8080

  