apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-config
data:
  # Users API
  USERS_ASPNETCORE_ENVIRONMENT: "Development"
  USERS_ASPNETCORE_URLS: "http://+:8081"
  USERS_CONNECTIONSTRING: "Host=postgres-user;Database=fcg_user_db;Username=postgres;Password=postgres123;"
  # Catalog API
  CATALOG_ASPNETCORE_ENVIRONMENT: "Development"
  CATALOG_ASPNETCORE_URLS: "http://+:8083"
  CATALOG_CONNECTIONSTRING: "Host=postgres-catalog;Database=fcg_catalog_db;Username=postgres;Password=postgres123;"
  # Payment API
  PAYMENT_ASPNETCORE_ENVIRONMENT: "Development"
  PAYMENT_ASPNETCORE_URLS: "http://+:8085"
  PAYMENT_CONNECTIONSTRING: "Host=postgres-payment;Database=fcg_payment_db;Username=postgres;Password=postgres123;"
  # Notification API
  NOTIF_ASPNETCORE_ENVIRONMENT: "Development"
  NOTIF_ASPNETCORE_URLS: "http://+:8087"
  # RabbitMQ common
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: "guest"
  RABBITMQ_PASSWORD: "guest"
  # JWT defaults
  JWT_ISSUER: "FCG.API"
  JWT_AUDIENCE: "FCG.WebApp"
  JWT_EXPIRY_MINUTES: "60"