apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  # Substitua pela sua chave real ou use `kubectl create secret generic jwt-secret --from-file=secrets/jwt_secret`
  jwt: 4g2Yi6B/8xs7BQXZ22j7tazUG5sLbnJJatpAWXbfiPE=
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres123"
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
type: Opaque
stringData:
  email: "admin@fcg.com"
  password: "admin123"