apiVersion: v1
kind: Service
metadata:
  name: postgres-user
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-user
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-catalog
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-catalog
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-payment
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-payment
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: users-api
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: users-api
---
apiVersion: v1
kind: Service
metadata:
  name: catalogs-api
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: catalogs-api
---
apiVersion: v1
kind: Service
metadata:
  name: payments-api
spec:
  type: ClusterIP
  ports:
    - port: 8085
      targetPort: 8085
  selector:
    app: payments-api
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-api
spec:
  type: ClusterIP
  ports:
    - port: 8087
      targetPort: 8087
  selector:
    app: notifications-api
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: pgadmin